package com.boz.model;

import java.util.Date;

public class BozUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boz_user.id
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boz_user.username
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boz_user.password
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boz_user.phone
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boz_user.email
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boz_user.created
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boz_user.updated
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boz_user.id
     *
     * @return the value of boz_user.id
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boz_user.id
     *
     * @param id the value for boz_user.id
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boz_user.username
     *
     * @return the value of boz_user.username
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boz_user.username
     *
     * @param username the value for boz_user.username
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boz_user.password
     *
     * @return the value of boz_user.password
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boz_user.password
     *
     * @param password the value for boz_user.password
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boz_user.phone
     *
     * @return the value of boz_user.phone
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boz_user.phone
     *
     * @param phone the value for boz_user.phone
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boz_user.email
     *
     * @return the value of boz_user.email
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boz_user.email
     *
     * @param email the value for boz_user.email
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boz_user.created
     *
     * @return the value of boz_user.created
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boz_user.created
     *
     * @param created the value for boz_user.created
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boz_user.updated
     *
     * @return the value of boz_user.updated
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boz_user.updated
     *
     * @param updated the value for boz_user.updated
     *
     * @mbggenerated Mon May 08 06:20:42 CST 2017
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}